### ISSUE TITLE
Generating TLS certificate Error

### ISSUE THREAD

**Issue by samleong123** [Jigsaw-Code/outline-server#805] opened 2021-02-04 14:02 UTC
Hi , i got a Oracle Cloud VPS which is useless for me , but for now i wanted to install Outline VPN and send the access key to those Myanmar people let them can access Facebook even two ISP (MPT & Telenor) has blocked access to Facebook.
But i got error when Generating TLS Cert.
OpenSSL has already installed
```
ubuntu@vpn:~$ sudo bash -c "$(wget -qO- --no-check-certificate https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... OK
> Verifying that Docker daemon is running ..... OK
> Creating persistent state dir ............... OK
> Generating secret key ....................... OK
> Generating TLS certificate ..................
Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
```
```
ubuntu@vpn:~$ openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Wed Dec  2 14:52:44 2020 UTC
platform: debian-amd64
options:  bn(64,64) rc4(8x,int) des(int) blowfish(ptr)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-OIe5k7/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific
```
Any solution?

**Comment by fortuna** [comment] 2021-02-11 17:52
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/776

The issue is that the script fails to get the public IP address because ipinfp.io is blocking Oracle cloud.
You need to manually specify the IP with the `--hostname` flag.

**Closed by fortuna** 2021-02-11 17:52 UTC

**Comment by Alex-AXO** [comment] 2023-03-14 07:55
Hello. I have same problem. 

I don't understand, where I need to add this flag (--hostname). Please, help.
