### ISSUE TITLE
How to get Outline apiUri and certSha256 output once again?

### ISSUE THREAD

**Issue by shumtravi** [Jigsaw-Code/outline-server#1274] opened 2023-01-24 18:53 UTC
I want to connect outline server to another outline manager instance on different OS. How can i get certSha256 from server console without reinstallation?

**Comment by murka** [comment] 2023-01-24 19:34
@shumtravi, the access credentials stored on `/opt/outline/access.txt`, if you not change volume store on docker.
So, you can use command `cat /opt/outline/access.txt` for get apiUrl and certSha256.

**Comment by maddyhof** [comment] 2023-04-25 19:38
Marking as a feature request for the ability to export server information from one Manager instance and import it into another.

**Comment by maddyhof** [comment] 2023-07-24 17:31
Closing as duplicate of #1223

**Closed by maddyhof** 2023-07-24 17:31 UTC
Labels: feature request

**Comment by oruchkin** [comment] 2024-08-11 19:57
Worked for me from `macbook` to `macbook`
you need to transfer
```shell
~/Library/Application Support/Outline Manager
```
