### ISSUE TITLE
How to disable Prometheus

### ISSUE THREAD

**Issue by zouchengli** [Jigsaw-Code/outline-server#1127] opened 2022-07-27 01:00 UTC
<img width="1506" alt="image" src="https://user-images.githubusercontent.com/27568522/181137861-f755531a-f593-493e-b155-295c8c69913d.png">

**Comment by ch3rrydrunk** [comment] 2023-06-15 20:53
Having. the same issue
with Disk reads up to 256 mb/s, 100% CPU and OOM killer

**Comment by maddyhof** [comment] 2023-06-26 15:00
Thanks for your feedback. Closing as a duplicate of #442.

**Closed by maddyhof** 2023-06-26 15:00 UTC
Labels: duplicate, feature request
