### ISSUE TITLE
No usage status for access keys on both Outline Manager and API

### ISSUE THREAD

**Issue by Mrhalix** [Jigsaw-Code/outline-server#435] opened 2019-05-29 11:14 UTC
So, it been a while since the data transfer usage is vanished from outline manager, for the first time i ignored it. now i really need to know whats going on.

Outline Manager just shows "...." instead of usage,
![image](https://user-images.githubusercontent.com/15522903/58552848-9c0e5b00-8228-11e9-976d-13e3e885d21c.png)

so i tried to get information from Management API URL. `https://THEMANAGEMENTURL/metrics/transfer`

and heres the response :
`{
code: "InternalServerError",
message: ""
}`

tell me your suggestions....

**Comment by fortuna** [comment] 2019-08-02 19:54
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/433

**Closed by fortuna** 2019-08-02 19:54 UTC
Labels: bug, manager
