### ISSUE TITLE
v2ray support please

### ISSUE THREAD

**Issue by malikshi** [Jigsaw-Code/outline-server#391] opened 2019-02-04 15:31 UTC
as you can see simple-obfs not deprecated and now come up with v2ray with many features, can you support this v2ray in outline?

[https://github.com/shadowsocks/v2ray-plugin](url)

**Comment by studentmain** [comment] 2019-02-04 15:46
https://github.com/Jigsaw-Code/outline-server/issues?utf8=✓&q=v2ray

**Comment by malikshi** [comment] 2019-02-04 16:00
> [https://github.com/Jigsaw-Code/outline-server/issues?utf8=✓&q=v2ray](https://github.com/Jigsaw-Code/outline-server/issues?utf8=%E2%9C%93&q=v2ray)

thanks.

**Comment by trevj** [comment] 2019-02-04 19:41
Duplicate of:
https://github.com/Jigsaw-Code/outline-server/issues/16

**Closed by trevj** 2019-02-04 19:41 UTC
