### ISSUE TITLE
Installing Outline via install_server.sh on a machine without Docker fails

### ISSUE THREAD

**Issue by evil-shrike** [Jigsaw-Code/outline-server#1014] opened 2021-11-21 23:33 UTC
For last couple of days I tried to install Outline server via the Outline Manager's suggested command on several machines. I tried Ubuntu and Debian, on gCloud and Azure. Every single time an installation failed.
The error I'm getting is:
GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8

```
shrike@vpn-outline2:~$ sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl https://get.docker.com/ | sh'. [Y/n] y
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/install for instructions.

Last error: # Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/ubuntu/gpg" | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
+ sh -c echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable" > /etc/apt/sources.list.d/docker.list
+ sh -c apt-get update -qq >/dev/null
W: GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu focal InRelease' is not signed.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_log3AJ
```

Before running the Outline's install_server.sh `sudo apt-get update` worked fine, but after it started failing with same error that happened for install_server.sh:
```
Err:4 https://download.docker.com/linux/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
```
Thankfully to [this post on SO](https://stackoverflow.com/questions/60137344/docker-how-to-solve-the-public-key-error-in-ubuntu-while-installing-docker) I found a workaround:
```
sudo chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
```

**Comment by daniellacosse** [comment] 2021-11-22 16:54
Possibly related? https://github.com/Jigsaw-Code/outline-server/issues/1005

**Comment by evil-shrike** [comment] 2021-11-23 21:41
Yeah, seems the same. But the issue isn't related to any cloud provider used, it's with the method install_server.sh uses to install Docker.

**Comment by legiorange** [comment] 2021-11-26 16:40
Here are the things .

Outline server install script uses get.docker.com  shell script .

Just ... install docker first.

**Comment by fortuna** [comment] 2022-01-06 17:24
Duplicate of #951

**Closed by fortuna** 2022-01-06 17:24 UTC
