### ISSUE TITLE
bandwidth remaining 0

### ISSUE THREAD

**Issue by someoneIG** [Jigsaw-Code/outline-server#906] opened 2021-05-28 20:55 UTC
Hi
My 3 servers have a problem
They don't count the traffic usage anymore :/

How can I solve this?
I didn't have this problem at first

https://pasteboard.co/K4JrnOr.png

**Comment by someoneIG** [comment] 2021-05-28 20:56
Hi
My 3 servers have a problem
They don't count the traffic usage anymore :/

**Comment by someoneIG** [comment] 2021-07-10 12:54
This isn't solved yet

**Comment by fortuna** [comment] 2021-08-17 22:41
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/953

**Closed by fortuna** 2021-08-17 22:41 UTC
