### ISSUE TITLE
Server running,but IP not changed on Windows10 

### ISSUE THREAD

**Issue by Edward7Zhang** [Jigsaw-Code/outline-server#49] opened 2018-03-26 15:07 UTC
This server running on Android devices well, same server on windows10 it can Connected,but IP not changed and can't visit google.com
This computer can ping my server ip well
Please update the .exe

**Comment by bemasc** [comment] 2018-03-26 15:32
What browser are you using?  Do you have a proxy extension installed in your browser?  A proxy extension could conflict with Outline's proxy settings.

**Comment by bemasc** [comment] 2018-03-26 15:34
Duplicate of https://github.com/Jigsaw-Code/outline-client/issues/34

**Closed by bemasc** 2018-03-26 15:34 UTC

**Comment by Edward7Zhang** [comment] 2018-03-26 16:34
I using Chrome and not installed proxy extension,i try many ways to check this problem out,but it not works.
