### ISSUE TITLE
Wrong icon display on macos

### ISSUE THREAD

**Issue by ErvingWu** [Jigsaw-Code/outline-server#452] opened 2019-06-25 17:03 UTC
![Screenshot 2019-06-26 at 01 01 04](https://user-images.githubusercontent.com/52124755/60118089-1f7e8600-97ae-11e9-9c10-720d9df27507.png)

**Comment by fortuna** [comment] 2019-08-02 18:58
@alalamav didn't we have this fixed? What was the workaround?

**Comment by cjhenck** [comment] 2020-06-08 21:23
Duplicate of #320

**Closed by cjhenck** 2020-06-08 21:23 UTC
Labels: bug, manager
