### ISSUE TITLE
create server on Oracle Cloud error

### ISSUE THREAD

**Issue by EhabEllawendy** [Jigsaw-Code/outline-server#1005] opened 2021-10-25 11:47 UTC
ubuntu@srvr-vpn:~$ sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
> Verifying that Docker is installed .......... NOT INSTALLED
> Would you like to install Docker? This will run 'curl https://get.docker.com/ | sh'. [Y/n] Y
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/install for instructions.

Last error: # Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sh -c apt-get update -qq >/dev/null
W: GPG error: https://download.docker.com/linux/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
E: The repository 'https://download.docker.com/linux/ubuntu focal InRelease' is not signed.

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /tmp/outline_log72U

**Comment by legiorange** [comment] 2021-11-10 15:55
These are easy things.
`sudo apt install docker.io`
It worked ubuntu 19+, I test it today.

**Comment by daniellacosse** [comment] 2021-11-11 15:26
Yeah, we're currently using the install script that docker provides but doesn't maintain 😅  It's a bit unclear how to proceed. Happy to take ideas 😁

**Comment by EhabEllawendy** [comment] 2021-11-18 12:52
> These are easy things. `sudo apt install docker.io` It worked ubuntu 19+, I test it today.

working fine thank you

**Comment by fortuna** [comment] 2022-01-06 17:24
Duplicate of #951

**Closed by fortuna** 2022-01-06 17:24 UTC
