### ISSUE TITLE
Clash with Squid proxy port: 9091

### ISSUE THREAD

**Issue by alashow** [Jigsaw-Code/outline-server#279] opened 2018-10-18 18:56 UTC
My server wasn't working so I checked the logs:
```ruby
I2018-10-18T18:27:14.804Z 9 main.js:121] Starting...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:9091
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1505:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
```

I checked what was using `9091`. It was [squid proxy](http://www.squid-cache.org/), which I was running on the same server.

I changed squid's port to something else and restarted outline docker. It's working okay now.

Is this an expected behavior?
https://github.com/Jigsaw-Code/outline-server/blob/d0c24172d3b825a24b854a432ecd18888bcef03b/src/shadowbox/infrastructure/get_port.spec.ts#L49-L53

I believe this behavior started after [this](https://quay.io/repository/outline/shadowbox/manifest/sha256:40cd66158be8b412dc49d3314304c93a345ae5bf388a9ea2f7c5030bf6cd9e87) image.

**Comment by alashow** [comment] 2018-10-18 19:05
Also, off-topic question, after the restart somehow traffic usage stats shown in Outline Manager has been reset. Is it also an expected behavior?

**Comment by trevj** [comment] 2018-10-18 20:20
@alashow Thanks for trying Outline and for the bug report.

@alalamav I thought Shadowbox would retry if ports 9090 and 9091 were reserved - any idea what's happening here?

**Comment by fortuna** [comment] 2018-10-18 20:32
@alashow , what does the logs say for
 `Prometheus is at ${prometheusLocation}`
`Node metrics is at ${nodeMetricsLocation}`
`outline-ss-server metrics is at ${ssMetricsLocation}`
?

The server code is supposed to assign those ports starting at 9090 and increment one by one. However, it's supposed to skip used ports, and the get_port.spec.ts tests show that:
https://github.com/Jigsaw-Code/outline-server/blob/dd3e3f7df23990cdbc6e58a73defe0f99fae21d0/src/shadowbox/infrastructure/get_port.spec.ts#L45-L46

Did you start the squid proxy before or after the outline server was started?

The metrics are not supposed to be reset. We are switching to prometheus metrics, but we still refer to the old metrics here:
https://github.com/Jigsaw-Code/outline-server/blob/dd3e3f7df23990cdbc6e58a73defe0f99fae21d0/src/shadowbox/server/main.ts#L174
https://github.com/Jigsaw-Code/outline-server/blob/dd3e3f7df23990cdbc6e58a73defe0f99fae21d0/src/shadowbox/server/manager_metrics.ts#L43

**Comment by alashow** [comment] 2018-10-18 21:41
> what does the logs say for

```ruby
I2018-10-18T18:28:15.499Z 9 main.js:121] Starting...
I2018-10-18T18:28:15.577Z 9 main.js:130] Prometheus is at localhost:9090
I2018-10-18T18:28:15.578Z 9 main.js:131] Node metrics is at localhost:9091
I2018-10-18T18:28:15.578Z 9 main.js:132] outline-ss-server metrics is at localhost:9092
```

> Did you start the squid proxy before or after the outline server was started?

Before. I am using docker, so watchtower updated it and recreated the container.

> The metrics are not supposed to be reset. We are switching to prometheus metrics, but we still refer to the old metrics here

I didn't do anything. I only changed squid's port and restarted the outline container (`docker restart shadowbox`). So it's probably a bug too?
When outline started working again, stats in Outline Manager was 0 bytes then it started incrementing from 0.
Diff of old stats returns nothing, meaning it hasn't been changed since the restart:
```sh
diff shadowbox_stats.json ~/shadowbox-old/persisted-state/shadowbox_stats.json
``

**Comment by wydwww** [comment] 2018-10-19 04:43
Same here. Happened yesterday. Port 9091 was originally used by transmission, and now I change transmission's default port.

**Comment by fortuna** [comment] 2018-10-19 15:17
I'm sorry for all the trouble.

We did anticipate that, and wrote code to prevent that, and tests to validate, but it seems it's not working as intended.

Here is my current guess: we rely on `lsof` to identify used ports. However, we run that on the docker image, and it may not be seeing the host ports. I'll try to validate that.

The solution I envision is to validate that a port is open by trying to open it, then close it before handing it to prometheus or shadowsocks.

**Comment by alashow** [comment] 2018-10-19 19:30
Thanks!
What about the stats issue? Shall I open a separate issue for tracking it?

**Comment by fortuna** [comment] 2018-10-19 19:35
I have a fix under review: #280
I expect to be able to release it today.

**Comment by alashow** [comment] 2018-10-19 19:45
> What about the stats issue? Shall I open a separate issue for tracking it?

I meant the stats/metrics resetting issue, if you were answering to that.

**Comment by fortuna** [comment] 2018-10-19 20:38
@alashow, #280 will fix that too.

**Comment by fortuna** [comment] 2018-10-19 21:05
Keeping it open until we release the fix.

**Comment by fortuna** [comment] 2018-10-19 21:50
Fix is pushed to production. Your server should see the update within 1 hour. You can force the update with `docker restart shadowbox`.

**Closed by fortuna** 2018-10-19 21:50 UTC
Labels: bug, prioritised

**Comment by alashow** [comment] 2018-10-19 22:01
Restarting the container doesn't update the image, right? Pulling the latest image and restarting the container doesn't work too, as the container needs to be recreated to use a new image (which I guess what `watchtower` does automatically).
And there is no way to trigger `watchtower` to update.

Do you know any other way on how to force update it?

**Comment by fortuna** [comment] 2018-10-19 22:19
This should work:
```
docker pull quay.io/outline/shadowbox:stable && docker restart shadowbox
```

**Comment by fortuna** [comment] 2018-10-20 00:36
@alashow when you run `docker ps`, do you get the shadowbox container with the `quay.io/outline/shadowbox:stable` image?

If not, you may be in a state that won't get updated. One thing you can try is to tag the image id that is being used to see if it goes back to the correct state:
```
docker tag <IMAGE_ID> quay.io/outline/shadowbox:stable
```
Watchtower should do the right thing and update it eventually.

If even that doesn't work, and you find yourself in a broken state, you may do a clean restart. The easiest way I can think of is this:
```bash
docker inspect --format '{{range .Config.Env}}{{println .}}{{end}}' shadowbox | grep SB_ > $HOME/shadowbox/run.env
docker stop shadowbox && docker rm shadowbox
docker run -d --name shadowbox --restart=always --net=host -v $HOME/shadowbox/persisted-state:$HOME/shadowbox/persisted-state --env-file=$HOME/shadowbox/run.env quay.io/outline/shadowbox:stable 2>&1 >/dev/null
```
I use `run.env` to restore the original environment. You'll need to keep that file around forever, or reproduce the env vars with the docker flags.

**Comment by alashow** [comment] 2018-10-20 00:49
> Watchtower should do the right thing and update it eventually.
It did. It's all good now

> @alashow when you run docker ps, do you get the shadowbox container with the quay.io/outline/shadowbox:stable image?

Yeah. After pulling the latest image, `docker image` was showing two `quay.io/outline/shadowbox` images, one with the tag `stable` and the other with `<none>` (i.e previous image pulled by `watchtower`). I think `shadowbox` container was using the latter, as described in the above link.

Thanks for your help!
