### ISSUE TITLE
install_server.sh with Ubuntu: curl command not found

### ISSUE THREAD

**Issue by kuznetsov-m** [Jigsaw-Code/outline-server#1156] opened 2022-08-26 14:01 UTC
```
> uname -a
Linux vm1910170 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
(...)
Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us
Full log: /tmp/outline_logd6i
```

Log:
```
Verifying that Docker is installed
NOT INSTALLED
^[[0;31mNOT INSTALLED^[[0m
> Would you like to install Docker? This will run 'curl https://get.docker.com/ | sh'. [Y/n] Installing Docker
> Installing Docker ........................... Docker installation failed, please visit https://docs.docker.com/install for instructions.
^[[0;31mDocker installation failed, please visit https://docs.docker.com/install for instructions.^[[0m
\nSorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us$
Full log: /tmp/outline_logd6i
environment: line 156: curl: command not found
```

`install_server.sh` script, after `curl` installation (`sudo apt install curl`), works correctly. However, it would be great to add a check for `curl`.

**Comment by sbruens** [comment] 2024-08-27 15:57
Closing as dupe of #1247

**Closed by sbruens** 2024-08-27 15:57 UTC
