### ISSUE TITLE
Outline Manager 1.15.1-universal can't be opened on macOS because of a notarization problem

### ISSUE THREAD

**Issue by kevin1** [Jigsaw-Code/outline-server#1474] opened 2024-01-18 09:57 UTC
I got the following error message when opening the latest Outline Manager (1.15.1) on macOS Sonoma. Download link used: https://s3.amazonaws.com/outline-releases/manager/macos/stable/Outline-Manager.dmg

<img width="372" alt="Screenshot 2024-01-18 at 1 35 37 AM" src="https://github.com/Jigsaw-Code/outline-server/assets/580013/b759e235-e88d-4674-9a1b-42a86d1d04fd">

> "Outline Manager" can't be opened because Apple cannot check it for malicious software.

I downloaded an older version, 1.14.0, which works.
Download link: https://github.com/Jigsaw-Code/outline-server/releases/tag/manager-v1.14.0 

<img width="535" alt="Screenshot 2024-01-18 at 1 35 23 AM" src="https://github.com/Jigsaw-Code/outline-server/assets/580013/fe3d665a-838c-44ee-a75e-0ba1924c31d0">

Here is a comparison of the `codesign` outputs showing the notarization was not stapled:

```
$ codesign --test-requirement="=notarized" --verify --verbose /Volumes/Outline\ Manager\ 1.15.1-universal/Outline\ Manager.app 
/Volumes/Outline Manager 1.15.1-universal/Outline Manager.app: valid on disk
/Volumes/Outline Manager 1.15.1-universal/Outline Manager.app: satisfies its Designated Requirement
test-requirement: code failed to satisfy specified code requirement(s)
$ codesign --test-requirement="=notarized" --verify --verbose /Volumes/Outline\ Manager\ 1.14.0/Outline\ Manager.app 
/Volumes/Outline Manager 1.14.0/Outline Manager.app: valid on disk
/Volumes/Outline Manager 1.14.0/Outline Manager.app: satisfies its Designated Requirement
/Volumes/Outline Manager 1.14.0/Outline Manager.app: explicit requirement satisfied
```

The notarization also cannot be stapled manually:

```
$ xcrun stapler staple /Volumes/Outline\ Manager\ 1.15.1-universal/Outline\ Manager.app 
Processing: /Volumes/Outline Manager 1.15.1-universal/Outline Manager.app
CloudKit query for Outline Manager.app (2/4c7f78d349ef2912c5404f2c5d18b323186e4366) failed due to "Record not found".
Could not find base64 encoded ticket in response for 2/4c7f78d349ef2912c5404f2c5d18b323186e4366
The staple and validate action failed! Error 65.
```

Related discussions:
- #543
- https://www.reddit.com/r/outlinevpn/comments/16wg8k1/hi_there_i_cant_install_outline_manager_on_my/

**Comment by sbruens** [comment] 2024-02-09 19:34
Duplicate of #1426

**Closed by sbruens** 2024-02-09 19:34 UTC
Labels: manager, need test, os/macos
