### ISSUE TITLE
Time limit for keys

### ISSUE THREAD

**Issue by drugoe-levo** [Jigsaw-Code/outline-server#1272] opened 2023-01-24 11:52 UTC
I would very much like to be able to limit the validity of the key by time in official manager (from the moment of the first connection or for a specific time)

**Comment by Joy096** [comment] 2023-01-24 13:38
Also it would be nice to be able to set an internet speed limit for every key and for all keys.
And ability to disable some keys but not delete them.

**Comment by ahmadipiralvan** [comment] 2023-01-28 07:25
Please go to the this issue and add your request:
https://github.com/Jigsaw-Code/outline-client/issues/1553

**Comment by maddyhof** [comment] 2023-07-24 17:32
Closing as duplicate of #1318

**Closed by maddyhof** 2023-07-24 17:32 UTC
Labels: feature request
