### ISSUE TITLE
[FEATURE REQUEST] Support multiple servers in Outline Manager

### ISSUE THREAD

**Issue by NightMachinary** [Jigsaw-Code/outline-server#190] opened 2018-07-06 17:40 UTC
PS: How can I get the string needed by Outline Manager to connect to the server from a server that was set up sometime before? `docker logs shadowbox`? Which line would I need then?

**Comment by fortuna** [comment] 2018-07-10 20:50
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/78

**Closed by fortuna** 2018-07-10 20:50 UTC

**Comment by fortuna** [comment] 2018-07-10 20:54
You can find the access config at `/root/shadowbox/access.txt`

**Comment by NightMachinary** [comment] 2018-07-18 09:46
@fortuna `cat: /root/shadowbox/access.txt: No such file or directory`
