### ISSUE TITLE
Transfer all users to another server

### ISSUE THREAD

**Issue by morteza102030** [Jigsaw-Code/outline-server#1363] opened 2023-06-20 14:21 UTC
hi
i need transfer all users key to another server 
i used domain instead of ip from first and ubuntu 22 and saved apiurl
transferring /opt/outline/persisted-state/ to new server not worked for me 
please add a Ability to we can transfer server simply

**Comment by maddyhof** [comment] 2023-08-30 19:36
Closing as a duplicate of #1268

**Closed by maddyhof** 2023-08-30 19:36 UTC
Labels: feature request, server
