### ISSUE TITLE
cannot connect to manual server in 1.1.9

### ISSUE THREAD

**Issue by chenhailong888** [Jigsaw-Code/outline-server#322] opened 2018-11-26 11:38 UTC
Your Outline Server was installed correctly, but we are not able to connect to it. Most likely this is because your server's firewall rules are blocking incoming connections. Please review them and make sure to allow incoming TCP connections on ports ranging from 1024 to 65535.
![1](https://user-images.githubusercontent.com/34810179/49011930-c8cab280-f1b2-11e8-8efc-5543f712d53d.JPG)
![2](https://user-images.githubusercontent.com/34810179/49011931-c9634900-f1b2-11e8-94ef-a68d410c0519.JPG)
![3](https://user-images.githubusercontent.com/34810179/49011932-c9634900-f1b2-11e8-87eb-f8bd3a23e5ec.JPG)

**Comment by chenhailong888** [comment] 2018-11-26 11:43
Version 1.1.9

**Comment by fortuna** [comment] 2018-11-29 15:45
Maybe your Google Cloud doesn't have a static external IP address? VMs don't get a static external IP address by default on Google Cloud. You need to request it.

On the networking tab, you need to select "Create IP Address" under "External IP".

![image](https://user-images.githubusercontent.com/113565/49233343-d3a86180-f3c3-11e8-8182-049a752f5982.png)

**Comment by chenhailong888** [comment] 2018-11-30 13:21
> 也许您的Google Cloud没有静态外部IP地址？默认情况下，虚拟机在Google Cloud上不会获得静态外部IP地址。你需要要求它。
> 
> 在网络选项卡上，您需要选择“外部IP”下的“创建IP地址”。
> 
> ![图片](https://user-images.githubusercontent.com/113565/49233343-d3a86180-f3c3-11e8-8182-049a752f5982.png)

![1](https://user-images.githubusercontent.com/34810179/49291563-b4a1f080-f4e5-11e8-93d5-bf387545e328.JPG)
![2](https://user-images.githubusercontent.com/34810179/49291566-b53a8700-f4e5-11e8-821c-4edcfa47fee8.JPG)
![3](https://user-images.githubusercontent.com/34810179/49291567-b53a8700-f4e5-11e8-893a-fd9ddd7ff99d.JPG)
  
Still not working

**Comment by fortuna** [comment] 2018-11-30 18:10
That's odd. I tried to reproduce the error by creating an Outline server on Google Cloud and it worked fine for me. I used Manager 1.1.9.

If you are in China, maybe the reason is because I believe Google Cloud is blocked in China, while DigitalOcean is not. You would have to connect to a VPN in order to manage a server on Google Cloud.

**Comment by trevj** [comment] 2018-11-30 19:37
@chenhailong888 It's interesting that an earler version of the server manager works for you. Perhaps if we can figure out the latest version of the server manager that works with your server, we will learn something. You already said it works with 1.1.14 but not 1.1.19 - if you have time to report back with which versions inbetween 1.1.14 and 1.1.19 work for you, that could be very helpful.

**Comment by chenhailong888** [comment] 2018-12-01 07:49
@fortuna
@trevj
I have tried again according to your steps, but it still doesn't work.

 I had no problem with version 1.1.4. My computer was Windows 7.

**Comment by joeylee202** [comment] 2018-12-02 12:18
> I have the same problem as chenhailong, 1.1.14 works, but 1.1.19 or 1.2 doesn't work. I'm am in Hong Kong, so i'm not behind the great firewall.
> 
> I also have the corrupt icon preview as well running El Capitan.
> 
> Keep up the good work!
> 
> _edit_
> I've downloaded and tried all versions, below are my findings on my Macbook Pro running El Capitan, with GC server set up in Hong Kong, again, i'm in Hong Kong so I'm not behind the great firewall. I've also tried shadowsocking to a USA based server first before running the outline server commands, but 1.1.9 and 1.2 still does not work.
> 
> 1.1.4 - works
> 1.1.5 - works
> 1.1.6 - works
> 1.1.7 - works
> 1.1.8 - works
> 1.1.9 - does not work (gives "unable to connect to outline server" error after pasting api code)
> 1.2 - does not work (gives "unable to connect to outline server" error after pasting api code)

Can I ask how do you download other versions of the software?

**Comment by fortuna** [comment] 2018-12-03 18:15
@hammiesam Thanks a lot for the incredible help!
You helped us pinpoint that the problem is.

It seems you all have spurious whitespace or line breaks in the code you are pasting into the dialog.
In https://github.com/Jigsaw-Code/outline-server/pull/315 we accidentally removed the code that ignored whitespaces in the pasted text.

You can make it work again by removing all the whitespace and line breaks in the text you paste into the box. We'll work on a fix for restore the more lenient behavior.

**Comment by trevj** [comment] 2018-12-03 20:56
@joeylee202 Thank you so much! This restores the previous behaviour:
https://github.com/Jigsaw-Code/outline-server/pull/332

Apologies for any inconvenience here.

**Comment by hammiesam** [comment] 2018-12-04 01:05
oh wow it's that simple, it works now in 1.2, thank you for adding the multi-server function!

**Comment by chenhailong888** [comment] 2018-12-04 01:33
@fortuna
@trevj
Thanks a lot

**Comment by zlfccnu** [comment] 2018-12-06 13:53
> @hammiesam @chenhailong888 Thanks a lot for the incredible help!
> You helped us pinpoint what the problem is.
> 
> It seems you all have spurious whitespace or line breaks in the code you are pasting into the dialog.
> In #315 we accidentally removed the code that ignored whitespaces in the pasted text.
> 
> You can make it work again by removing all the whitespace and line breaks in the text you paste into the box. We'll work on a fix for restore the more lenient behavior.

Hi @fortuna I have the same problem and I solved it with the following procedure as I have commented under #277 

I check the info from both ~/shadowbox/access.txt and ~/shadowbox/access.txt.bak. The actual problem is that the info from both files are somehow inconsistent:
from access.txt, I only have certSha256
from access.txt.bak, I actually have the apiUrl and certSha256
both certSha256 are different.
I manage to solve that problem by replacing the certSha256 in file access.txt.bak with certSha256 in file access.txt
I suspect that the problem is once I forget the server, the outline server will regenerate a new credential but without new apiUrl. Thus the old string is invalid.

**Comment by fortuna** [comment] 2018-12-06 16:31
@zlfccnu it seems the issue you had was different from the issue here

The fix for this issue has been released, so we can close it.

**Closed by fortuna** 2018-12-06 16:31 UTC
Labels: advanced install, prioritised
