### ISSUE TITLE
Linux client keeps on reconnecting

### ISSUE THREAD

**Issue by glow12121** [Jigsaw-Code/outline-server#1573] opened 2024-08-10 14:43 UTC
My Outline client on Fedora 39 keeps on reconnecting to the virtual server:

[Screencast from 2024-08-10 17-40-52.webm](https://github.com/user-attachments/assets/6735ca40-f346-4e8e-ac34-de15f5fc1fa2)

Despite this, speedtest.net shows decent connection speed:

![image](https://github.com/user-attachments/assets/d5ef7860-d242-43b9-968f-39d3d42e3576)

How could I further diagnostize the problem? Thanks.

**Comment by sbruens** [comment] 2024-08-27 19:30
Closing as dupe of #2092

**Closed by sbruens** 2024-08-27 19:30 UTC
Labels: os/linux, support new platform
