### ISSUE TITLE
Feature request: export and import for migration

### ISSUE THREAD

**Issue by alexlii1971** [Jigsaw-Code/outline-server#1107] opened 2022-06-04 09:37 UTC
Hello,

On outline manager, it would be great if it support to export and import all the settings by a XML or Json file for migration between windows and Mac.

Thanks

**Comment by Alibabasamand1359** [comment] 2022-10-04 23:05
Edvard

**Comment by Alibabasamand1359** [comment] 2022-10-04 23:05
Edvarf

**Comment by maddyhof** [comment] 2023-07-24 17:31
Closing as duplicate of #1223

**Closed by maddyhof** 2023-07-24 17:31 UTC
Labels: feature request
