### ISSUE TITLE
Outline Manager icon preview - inside an app folder - appears corrupted "corrupted" on macOS Mojave

### ISSUE THREAD

**Issue by irlcatgirl** [Jigsaw-Code/outline-server#320] opened 2018-11-23 03:28 UTC
The Outline Manager icon, when inside an app folder on macOS Mojave. Appears to be corrupted. This only happens with the folder preview and it's fine when displayed elsewhere. Would appreciate if the Outline Devs could look into this ❤️ 
<img width="1280" alt="screen shot 2018-11-22 at 10 26 00 pm" src="https://user-images.githubusercontent.com/8227641/48927665-c4965080-eea5-11e8-878d-453f48630db8.png">

**Comment by fortuna** [comment] 2018-11-29 15:47
@nsuchy I'm sorry for the issue.
@alalamav Did we ever figure out what the problem is?

**Comment by trevj** [comment] 2018-11-30 20:07
@nsuchy I just upgraded to Mojave but I'm not seeing this issue. Did you install the manager by copying to Applications?

**Comment by nsuchy** [comment] 2018-11-30 20:11
Yes. Did you put the app in a folder?

**Comment by alalamav** [comment] 2018-11-30 20:57
This issue was originally reported in [electron-builder/#2533](https://github.com/electron-userland/electron-builder/issues/2533) and fixed in `electron-builder`. We rely on [electron-icon-maker](https://github.com/jaretburkett/electron-icon-maker) to generate icons, but it hasn't been updated in a while, so the bug may be present there.
Seems to me like we need to find an alternative to generate the icons, or use electron-builder to do so.

**Closed** 2022-01-19 22:48 UTC
Labels: need more info
