### ISSUE TITLE
Pihole

### ISSUE THREAD

**Issue by TarekSalama** [Jigsaw-Code/outline-server#872] opened 2021-04-20 15:02 UTC
Hello,

Is there a way to integrate Pihole with Outline like you can with PiVPN?

Thanks!

**Comment by JonathanDCohen** [comment] 2021-04-27 17:44
Hey there!

What exactly are you trying to do with PiHole?  People have attempted to run a server on a Raspberry Pi but we don't test it on ARM.

**Comment by TarekSalama** [comment] 2021-04-27 17:46
So if you attempt to install PiVPN on a VPS that has Pihole installed, it will use Pihole to block ads.
I was looking for a way to do the same with Outline.

**Comment by JonathanDCohen** [comment] 2021-04-28 16:32
As I understand it, PiHole acts as your DNS resolver in order to block ads.  

outline-client resolves DNS using a hardcoded list of resolvers.  IIUC you'd have to go in and make a custom build of outline-client using your VPS's public IP address as the resolver IP

**Comment by TarekSalama** [comment] 2021-04-28 16:34
Any chance you guys could add it in the Outline Manager in the future so that it would be dynamic instead of hardcoded?

**Comment by sbruens** [comment] 2024-08-27 15:11
Closing as duplicate of https://github.com/Jigsaw-Code/outline-apps/issues/568

**Closed by sbruens** 2024-08-27 15:11 UTC
Labels: question
