### ISSUE TITLE
Websockets traffic not stable over Outline (possible keepalive issue)

### ISSUE THREAD

**Issue by mountaindude** [Jigsaw-Code/outline-server#85] opened 2018-04-10 20:58 UTC
I have Outline set up nicely on a small dedicated Google GCP server. There are GCP firewall rules allowing any traffic coming into the Outline server to be sent to other servers in the same GCP network.

I access services running on those other GCP servers, via the Outline server, from Chrome on my Macbook. These services use websockets to send data in real-time from the server to my web browser. 
Works fine for a while, but after a minute or two the websocket connection drops, and the browser page has to be reloaded. Repeat again and again.

Seems Outline is just not (yet) very stable wrt websockets... Or could I be suffering from some other phenomena?

I have tried upgrading the Outline server to a larger one, in case it was overloaded and caused packet drops - nothing changed.

**Comment by fortuna** [comment] 2018-05-01 16:42
Thanks for the report. This is the first time we hear about this issue.
How can we reproduce the problem so we can investigate? Do you see the same issue with https://websocket.org/echo.html ? If not, is the website you are experiencing this issue with public?

**Comment by mountaindude** [comment] 2018-05-01 17:50
I'll test against that site too, to see if I can reproduce it. 
I am on a 250 MBit fiber connection, low latency etc. So it's not a matter of a poor connection.

I noticed the issue when connecting to a Qlik Sense (business intelligence tool/platform) cluster running on a couple of Google cloud servers (running Windows Server 2016), using Outline on a Linux box as VPN gateway into the GCP cluster.
The servers are thus not publicly available. 

For what it's worth, I also tried spinning up Algo VPN on an indentical Linux box in that same GCP cluster, works a treat even when I have really stressed the connection/servers.

So... not sure what I can recommend for reproducing the issue.. If you have some ideas on what I should look out for I am happy to do so and report back, but I fully understand that's a pretty poor way of debugging issues..

**Comment by fortuna** [comment] 2018-05-01 19:33
I think we have a suspicion: we probably need to set up TCP keep-alive in either the Outline server or client. We'll investigate more.

**Comment by fortuna** [comment] 2018-05-03 04:09
@alalamav @bemasc : It seems shadowsocks-libev doesn't enable keep-alive, except in the "redir" mode, which we don't use:
https://github.com/shadowsocks/shadowsocks-libev/search?utf8=%E2%9C%93&q=alive&type=

I don't know if there's a reason for that. It might be a nice change to upstream.

**Comment by fortuna** [comment] 2018-05-03 04:11
@madeye is there a reason for shadowsocks-libev to not set up tcp keep-alive in regular client or server mode?

**Comment by madeye** [comment] 2018-05-03 08:11
Enlarge the default timeout to 600 seconds. Otherwise, the connection will be killed automatically.

Also make sure both server and client's timeouts are set to be larger than 600s.

**Comment by mountaindude** [comment] 2018-05-14 20:09
@fortuna I just wanted to check in to see if there is something I can contribute with. I am not much of a VPN developer, but happy to test stuff if needed.

Also, I realised that the ws timeout seems to arrive pretty close to 60 sec after the session is established. Could be a conincidence, or there is a 60 sec timeout somewhere that should be (much) longer?

**Comment by themirrortruth** [comment] 2018-05-21 01:51
Maybe it could be useful:
http://coryklein.com/tcp/2015/11/25/custom-configuration-of-tcp-socket-keep-alive-timeouts.html

**Comment by fortuna** [comment] 2018-06-13 16:06
@madeye would a keep-alive be enough? I'd think it would prevent the timeout. Why is a larger timeout better?

**Comment by Matvey-Kuk** [comment] 2018-07-30 19:58
I experience similar issue with SSH and MySQL connections. :(

**Comment by tlghnb** [comment] 2018-08-11 15:29
I have the same issue too. It keeps dropping SSH connection after a minute.

**Comment by fortuna** [comment] 2018-08-22 15:40
We're looking into this issue. @madeye why do we need a timeout at all? Couldn't disconnections of idle connections be driven by the client or server?

**Comment by madeye** [comment] 2018-08-23 01:50
Timeout is a parameter you can tune for both client and server.

For a high load server, a small timeout would improve the overall performance a lot.

**Comment by tlghnb** [comment] 2018-08-23 07:49
How do I tune timeout parameter? I couldn't find any config file or something.

**Comment by Matvey-Kuk** [comment] 2018-08-23 11:44
@madeye in my case timeout is a show-stopper for users. They actively use SSH, Ansible, MySQL and other tools which are sensitive for connection reliability. I'm not sure what is the philosophy of the project but it could be nice to make it a universal tool for everyone 😃

**Comment by fortuna** [comment] 2018-08-23 16:10
@Matvey-Kuk: Outline sets the timeout parameter on the ss-local and ss-server calls. (BTW, @madeye is the owner of shadowsocks-libev. He doesn't work for Outline.)

We currently use the default of 60s in both the server and the client. Users can't toggle that, but we intend to make that change. It's still unclear what number we should use.

On the client side (ss-local), I don't see a good reason for the timeout, so we'll probably set it quite high (INT_MAX?).
On the server side, my understanding is that it's useful against DDoS attacks or rogue clients. @madeye recommended 10m, but I don't know if that's enough for SSH and other applications. @madeye : To make sure I understand: the timeout is for idle connections right? If there's activity the connections will last past the timeout?

**Comment by Matvey-Kuk** [comment] 2018-08-24 14:04
@fortuna about timeout value I can share my case: users expect connection without timeouts at all =( They open SSH connections and return to them from time to time during working day.

**Comment by caljorden** [comment] 2018-09-06 04:49
@fortuna: I am experiencing the same issue with SSH timeouts.  Your understanding is correct that it is only for idle connections (i.e. ones where the user is not sending or receiving any data).  I have also validated that the issue continues to occur after the client update was installed on my Mac with the ss-local timeout changed to INT_MAX.

Would it make sense to allow the timeout to be configurable in the outline manager application?  I think a default of 1 hour or something reasonably high might be good, but in some cases (like mine), I would prefer it to be more than that (probably 2 hours or more).  Even a fix of one hour would really help in my situation.

**Comment by fortuna** [comment] 2018-09-06 05:00
Thanks for the feedback @caljorden 

Even though we increased the timeout on the client-side, we haven't fixed the server yet.
We are moving to use [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server), which won't have a timeout (the connection closing will be driven by the endpoints only).

If you'd like to check if outline-ss-server fixes for you, you can run that server on your own, or access this prototype server I have running in London: https://s3.amazonaws.com/outline-vpn/invite.html#ss%3A%2F%2FY2hhY2hhMjAtaWV0Zi1wb2x5MTMwNTp5bXJnZ2ZLZWFXR3U%3D%40167.99.202.119%3A61434%2F%3Foutline%3D1

If you try, please let me know how it goes. Keep in mind I'll revoke the key without notice.

**Comment by caljorden** [comment] 2018-09-07 15:30
@fortuna: I just verified that with your London server the SSH timeout was not occurring for me.  I waited almost 5 minutes without any activity and did not see it disconnect.  Thus, the new outline-ss-server fixes the issue.  Thank you for your work on this!  Any idea when the outline-ss-server will be rolled out to outline manager configured servers?

**Comment by vysec** [comment] 2018-09-08 12:45
I use the normal client, connecting to your server. I still get SSH timeouts.

**Comment by fortuna** [comment] 2018-09-08 14:50
@caljorden Thanks for the feedback. We still need to integrate outline-ss-server with the Outline Server code. Getting metrics to work and making things backward compatible are kind of a pain. I'm hoping to have a public version within 3-4 weeks.

@vysec What platform is your Outline client, and what version?

**Comment by vysec** [comment] 2018-09-08 15:35
Latest Windows version available as a release on the outline-client repo.

**Comment by dsk9** [comment] 2018-09-20 14:56
I have the same issue too by sending telegram on android . but now use shadosocks chacha20 ,and add server on  outline not problem timout .

**Comment by vysec** [comment] 2018-11-11 18:55
Any updates on this? It's being a major issue these days. I can't keep a connection alive unless I pipe something through it.

**Comment by fortuna** [comment] 2018-11-20 23:47
@vysec We've removed the timeout from the Outline Client already, but not the server yet.

We are in the process of replacing the server Shadowsocks implementation, from [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev) to [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server). The new implementation does not have a timeout and should fix this issue. We've rolled out the change to 30% of the servers, but maybe the one you use is not in that 30%. We'll finish the rollout next week, after Thanksgiving in the US.

Do you own the server that you are using? If so, it's possible to force the new implementation so you can see if it fixes the problem for you. You would have to edit `shadowsocks_server_config.json` to add `"rollouts":[{"id": "outline-ss-server", "enabled": true}]`, then restart with `docker restart shadowbox`. To revert, just delete what you added and restart again.

**Comment by tlghnb** [comment] 2018-11-21 08:05
this is simply works! 🎉

**Comment by vysec** [comment] 2018-11-22 06:37
> @vysec, I'm sorry for the inconvenience. We've removed the timeout from the Outline Client already, but not the server yet.
> 
> We are in the process of replacing the server Shadowsocks implementation, from [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev) to [outline-ss-server](https://github.com/Jigsaw-Code/outline-ss-server). The new implementation does not have a timeout and should fix this issue. We've rolled out the change to 30% of the servers, but maybe the one you use is not in that 30%. We'll finish the rollout next week, after Thanksgiving in the US.
> 
> Do you own the server that you are using? If so, it's possible to force the new implementation so you can see if it fixes the problem for you. You would have to edit `shadowsocks_server_config.json` to add `"rollouts":[{"id": "outline-ss-server", "enabled": true}]`, then restart with `docker restart shadowbox`. To revert, just delete what you added and restart again.

Definitely not an inconvenience, we're not exactly paying for your time, are we? Thank you for your hard work!

**Comment by vysec** [comment] 2018-12-21 00:53
Hey, any updates on this issue?

**Comment by trevj** [comment] 2019-01-08 13:13
@vysecurity Apologies for the slow reply. This feature has been rolled out to all users for a weeks now. It seems like the issue is fixed for @tlghnb - if you're still experiencing issues, please comment re-open. Thanks!

**Comment by mountaindude** [comment] 2019-01-08 15:45
Late to the party here, but as I was the one to open this ticket, I figured it'd be nice to verify from my end too that things are now working as expected. Thanks everyone!!

**Comment by trevj** [comment] 2019-01-08 16:05
@mountaindude Thank you very much for folloiwing up! Delighted it's now working for you.

**Comment by vysecurity** [comment] 2019-01-08 16:21
Would be nice if everyone can let us know how they got it working. Because
on my end it still isn’t working.

**Comment by vysecurity** [comment] 2019-01-08 16:21
I’ve reinstalled outline many time’s. My SSH connecitons still die after
10/15 seconds of inactivity.

**Comment by fortuna** [comment] 2019-01-08 17:01
@vysecurity I'm sorry you are still seeing issues.

What's the error message you get when the connection dies?

Can we rule out that it's not your SSH configuration? Does the SSH connection stay up when not using the VPN?  Have you tried something like this: https://patrickmn.com/aside/how-to-keep-alive-ssh-sessions/?

**Comment by vysecurity** [comment] 2019-01-08 17:50
Yep, I’ve set that in SSH configuration and on client and server side.

I don’t have this issue when outline is off. Only when it is on.

**Comment by vysecurity** [comment] 2019-01-08 19:40
It just times out. It says SSH timeout I think. I’ll get a more verbose
reply tomorrow.

I’ve been running SSH in -vv mode recently because of this.

**Comment by vysecurity** [comment] 2019-01-09 17:04
![image](https://user-images.githubusercontent.com/3596242/50915360-967bc880-1473-11e9-9de1-6e705234934d.png)
This is what I'm seeing. Using Outline. It cuts off moments later (maybe 15 seconds max)

**Comment by vysecurity** [comment] 2019-01-09 17:10
Even with your UK server, it times out. Around ~ 30 seconds transferred if I don't type anything or send any input after I connect.

**Comment by helnokaly** [comment] 2019-01-17 10:33
SSH connections still dies in less than 30 seconds while using Outline.

**Comment by vysecurity** [comment] 2019-01-17 10:34
Set keepalive to 1 second

**Comment by vysecurity** [comment] 2019-01-17 10:34
That’s my temporary solution

**Comment by helnokaly** [comment] 2019-01-31 10:18
The websockets echo test ( http://www.websocket.org/echo.html ), disconnects in aprox 28 secs
![image](https://user-images.githubusercontent.com/15964842/52044412-cdad3900-254a-11e9-92f9-60e7686e7db9.png)

SSH connections disconnects also in aprox 28 secs
![screenshot from 2019-01-22 21-10-02](https://user-images.githubusercontent.com/15964842/51559600-fff3d200-1e8a-11e9-90d0-2085fc58083d.png)

Client: v1.0.5 (Ubuntu 18.04.1 LTS)
Server: outline-ss-server

Any updates on this issue? @fortuna

**Comment by vysecurity** [comment] 2019-01-31 10:33
Maybe there’s a websocket keepalive function? Set that to 5 seconds.

**Comment by xuyan2018** [comment] 2019-04-21 16:51
![111](https://user-images.githubusercontent.com/38712502/56473049-8c1c9200-6498-11e9-9133-e3019a156ceb.jpg)
someone can fix this problem?  I was troubled by this problem for a long time.

**Comment by vysecurity** [comment] 2019-04-21 17:58
Reduce keep alive

**Comment by xuyan2018** [comment] 2019-04-22 08:35
my ssh client have 1000+ server, need config one by one, have other way?

**Comment by vysecurity** [comment] 2019-04-23 03:02
Automate it

**Comment by sercba** [comment] 2019-05-08 00:15
Sorry. Any updates on this issue? Thanks!

**Comment by vysecurity** [comment] 2019-05-08 03:32
Change the keep alive to 1 second.

**Comment by fortuna** [comment] 2019-05-08 16:36
The Outline server and the clients no longer have a timeout, and the server enables TCP keep alive on both the connection with the client and the connection with the destination. I don't understand why you would be seeing this issue.

@sercba @xuyan2018 Are you using a non-Outline Shadowsocks server or client?

**Comment by xuyan2018** [comment] 2019-05-08 16:40
i using outline server. and client is download in getoutline.org.

**Comment by xuyan2018** [comment] 2019-05-08 16:41
if i no use outline. no problem. when i use outline. have this problem.

**Comment by sercba** [comment] 2019-05-08 18:08
> The Outline server and the clients no longer have a timeout, and the server enables TCP keep alive on both the connection with [the client](https://github.com/Jigsaw-Code/outline-ss-server/blob/8972cd64904d445b27bfb7efd083f1d3bc5bbf29/shadowsocks/tcp.go#L176) and the connection with [the destination](https://github.com/Jigsaw-Code/outline-ss-server/blob/8972cd64904d445b27bfb7efd083f1d3bc5bbf29/shadowsocks/tcp.go#L140). I don't understand why you would be seeing this issue.
> 
> @sercba @xuyan2018 Are you using a non-Outline Shadowsocks server or client?

@fortuna I use the standards Outline applications. But the server is a my own dedicated VPS (but following the Manager instructions).

How can I do to know if my Outline server software is in the last version?

Thank you! (sorry for my english)

**Comment by helnokaly** [comment] 2019-05-08 21:27
I still have this issue as described above https://github.com/Jigsaw-Code/outline-server/issues/85#issuecomment-459291315

Retested using Outline client v1.0.6 Linux

**Comment by helnokaly** [comment] 2019-05-17 11:40
Can this issue at least get confirmed and triaged?
Me and others here have provided some information above about server/client version and OS used.
What other info is needed ?

@fortuna

**Comment by xuyan2018** [comment] 2019-05-22 02:47
i changed my ssh client all session keepalive time to 10s , ssh can use it.   but my skype still have problem. if  i leave a little time, skype will display connecting....

**Comment by sercba** [comment] 2019-05-22 02:51
Me too. Linux client.

**Comment by vysecurity** [comment] 2019-05-22 03:57
Maybe they don’t have the issue in US or wherever. I recommend sending
someone to a censored country to do some investigation to try outline from
that perspective. Perhaps the keep-alive bug doesn’t show in US?

**Comment by raphaelfumfahr** [comment] 2019-05-25 11:56
I have the same error, my outline-server is located in Germany. The connection breaks every ~30 seconds.

**Comment by fortuna** [comment] 2019-05-28 22:13
People, please report the platform and exact version number of the client you are using.

Since January, I only saw reports of users using the Linux client, so I'm assuming this is Linux only.
Is SSH and Websockets unstable on other clients?

**Comment by sercba** [comment] 2019-05-28 23:15
Xubuntu 18.04.2 LTS - Outline 1.0.7.

**Comment by vysecurity** [comment] 2019-05-29 00:37
I’m on Windows 10. Same issue.

**Comment by ariebrainware** [comment] 2019-05-29 04:24
Debian Buster - Outline 1.1.0
Same issue, get disconnected after ~15s. Company VPS (Outline server) in SG.

@fortuna

**Comment by raphaelfumfahr** [comment] 2019-05-29 08:27
Sorry @fortuna 

My outline servers run under Ubuntu 18.04.2 in Germany and Finland.
The client is running on Windows 10 with version 1.2.32.
On both locations the same bug/error.

**Comment by ericrange** [comment] 2019-06-02 18:30
Windows 10, same issue.

**Comment by vysecurity** [comment] 2019-06-03 00:03
I believe this issue ties into the keep-alive issue to be honest. It’s
probably also one reason why voIP isn’t as good and keeps cutting.

**Comment by fortuna** [comment] 2019-06-04 19:12
Thank you all.
It seems that this is an issue specific to our Electron-based clients: Windows and Linux.

I checked whether we were disabling the timeout for ss-local, but it seems we are:
https://github.com/Jigsaw-Code/outline-client/blob/91a46da368f35faffa4b81efa6919fd334206224/src/electron/process_manager.ts#L340

@alalamav any ideas? Maybe it's something to do with tun2socks?

**Comment by water2fire** [comment] 2019-07-09 07:04
use line or skype, and some im software, still have this problem.

**Comment by morningk123** [comment] 2019-07-16 05:13
This problem has plagued me for a long time. Can someone solve it?

**Comment by fortuna** [comment] 2019-07-22 20:09
It seems @alalamav found the problem. We're working on a fix.

**Comment by alalamav** [comment] 2019-07-22 20:30
Hi all, we're updating the Outline clients to shadowsocks-libev v3.3.0, which disables client timeouts. We have also removed the user connection timeout from the Linux and Windows clients. I have verified that with this update ssh and websockets do not timeout anymore. 
I'll follow up on this thread once the fix has been merged/released.

**Closed** 2019-07-31 21:31 UTC
Labels: need more info, server

**Comment by fortuna** [comment] 2019-08-12 23:03
Windows client v1.2.34 and Linux client v1.0.10 should have the issue fixed.
Please let us know if you are still having problems.

**Comment by helnokaly** [comment] 2019-08-15 01:32
Fixed. Thanks.
