### ISSUE TITLE
Windows Outline Manager Client crashes upon open

### ISSUE THREAD

**Issue by npcingham** [Jigsaw-Code/outline-server#282] opened 2018-10-23 06:11 UTC
Windows 10 pro Build 17763.104
When launching Outline Manager, connected to a server on AWS, it launches, flashes up with the getting started menu and then proceeds as expected showing my two active keys. A few seconds later the program crashes.

Are there logs I should be checking somewhere?

**Comment by alalamav** [comment] 2018-10-25 18:18
@npcingham, sorry that you're experiencing this issue. Unfortunately, I was not able to reproduce on a Windows 10 machine. If possible, could you please submit feedback through the app (flag it with this issue ID)? Thanks.

**Comment by trevj** [comment] 2018-11-05 17:14
@sandrigo Sounds like the same issue you've been facing.

**Comment by trevj** [comment] 2018-11-08 14:35
@npcingham FYI we've been able to reproduce the issue on our systems and I'll be updating here as I know more.

**Comment by trevj** [comment] 2018-11-08 21:56
@npcingham I just merged https://github.com/Jigsaw-Code/outline-releases/pull/84 which should workaround the issue for now - many thanks again for the bug report and I hope this helps you get back up and running with the server manager.

**Closed** 2018-11-12 20:17 UTC
Labels: bug, prioritised

**Comment by npcingham** [comment] 2018-11-13 03:00
@trevj You're welcome. Thank you for fixing. Confirming V1.18 works!

**Comment by trevj** [comment] 2018-11-13 13:51
@npcingham Delighted to hear it :-)
