### ISSUE TITLE
Get an access key (by api)

### ISSUE THREAD

**Issue by prok0l** [Jigsaw-Code/outline-server#1398] opened 2023-08-30 21:50 UTC
I send GET request to url/{secretKey}/access-keys and see response, but when i send GET request with argument (id) url/{secretKey}/access-keys/0 i see this error
```
{
    "code": "MethodNotAllowed",
    "message": "GET is not allowed"
}
```

**Comment by maddyhof** [comment] 2023-09-01 15:07
Closing as a duplicate of #1331

**Closed by maddyhof** 2023-09-01 15:07 UTC
