### ISSUE TITLE
Access key per device or one session per access key

### ISSUE THREAD

**Issue by Mandofskii** [Jigsaw-Code/outline-server#928] opened 2021-06-17 21:09 UTC
Hi
I know there is issue with this title but you dont response on it

When this feature be available?

**Comment by bemasc** [comment] 2022-04-06 15:04
Closing as duplicate of #546.  Please keep discussion there.

In general, note that this feature is not strictly possible.  Generic user devices do not have an unforgeable device identity that could be authenticated by the server, nor do they have a stable network identity that could be used to prevent simultaneous access.

Approximate and insecure implementations of this feature are possible, but the resulting behavior could be confusing or unsafe for users and administrators, so it will need careful design.

**Closed by bemasc** 2022-04-06 15:04 UTC
Labels: duplicate
