### ISSUE TITLE
Connection speed limitation

### ISSUE THREAD

**Issue by KyleStance** [Jigsaw-Code/outline-server#1400] opened 2023-09-06 07:31 UTC
I have a gigabit tariff, and outline allows 1 user to eat the whole gigabit, please make it possible to set a global limit for example 150 mbit and a limit for each individual user.

**Comment by maddyhof** [comment] 2023-09-06 14:42
Closing as duplicate of #1246

**Closed by maddyhof** 2023-09-06 14:42 UTC
