### ISSUE TITLE
Feature request: Outline Manager for Android

### ISSUE THREAD

**Issue by GoGoogle** [Jigsaw-Code/outline-server#106] opened 2018-04-21 04:11 UTC
In many occasions, mobile phones have become the main force.So it can be introduced outline manager of Mobile client.For easy management.Thank you

**Comment by 4044ever** [comment] 2018-04-22 00:37
You better write that message in 中文. The translation failed.

**Comment by cybort** [comment] 2018-04-27 09:12
He asks if there will be Outline manager on Android.

**Comment by GoGoogle** [comment] 2018-04-27 09:41
@cybort yes,thank you.

**Comment by 4044ever** [comment] 2018-04-29 06:05
IMHO an outline manager for Android is a wonderful idea!

If that is possible I like to add:

- multi-server support
- a safe way to share keys (add BT i.e.)

AWS does work in China but can be blocked anytime. And problem is how you transfer the key safely? People in China typically have no WhatsApp and WeChat is government monitored. QR creating/reading would be handy for a Android manger/client.

**Comment by faridcboy** [comment] 2018-05-11 07:25
+1 
An outline manager for mobile devices could be the thing!

**Comment by laosb** [comment] 2018-05-15 00:43
@4044ever Related: #89 #94

**Comment by fortuna** [comment] 2018-06-12 19:04
Duplicate of https://github.com/Jigsaw-Code/outline-server/issues/153
Please follow it there.

**Closed by fortuna** 2018-06-12 19:04 UTC
Labels: component:manager, enhancement
